default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: come2coffee

development:
  <<: *default
  database: come2coffee_development
  password:

test:
  <<: *default
  database: come2coffee_test
  password: