default: &default
  host: <%= ENV["POSTGRESQL_HOST"] || "localhost" %>
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres

development:
  <<: *default
  database: come2coffee_development
  password:

test:
  <<: *default
  database: come2coffee_test
  password:
